const {chromium}=require("playwright");
(async()=>{const b=await chromium.launch({...(process.env.CHROMIUM?{executablePath:process.env.CHROMIUM}:{}),args:["--autoplay-policy=no-user-gesture-required"]});
  const ctx=await b.newContext({viewport:{width:1180,height:820}});const p=await ctx.newPage();const errs=[];p.on("pageerror",e=>errs.push(e.message));
  await p.addInitScript(()=>{window.__tts=[];const o=speechSynthesis.speak.bind(speechSynthesis);speechSynthesis.speak=u=>{window.__tts.push(u.text);};});
  const ok=(c,m)=>console.log((c?"PASS ":"FAIL ")+m);
  await p.goto("http://localhost:8804/");await p.waitForTimeout(2500);
  await p.evaluate(()=>document.querySelectorAll(".overlay.on").forEach(o=>o.classList.remove("on")));
  const keys=await p.evaluate(async()=>{await VoicePack.load();const idx=await (await fetch("voice/index.json")).json();return Object.keys(idx);});
  const word=keys.find(k=>!k.includes(" ")&&k.length>2),sent=keys.find(k=>k.split(" ").length>4);
  console.log("   testing:",word,"|",sent);
  const r=await p.evaluate(async([w,s])=>{window.__tts=[];const t0=performance.now();await Sound.say("word:"+w,w,.82);const t1=performance.now();
    await Sound.speak(s);const t2=performance.now();return{tts:window.__tts.slice(),wordMs:Math.round(t1-t0),sentMs:Math.round(t2-t1)};},[word,sent]);
  ok(!r.tts.length&&r.wordMs>200&&r.sentMs>500,"word and sentence play from the game voice, not the device: "+JSON.stringify(r));
  const r2=await p.evaluate(async()=>{window.__tts=[];await Sound.speak("Zebras juggle marmalade quietly.");return window.__tts;});
  ok(r2.length===1,"unknown line falls back to the device voice");
  await p.evaluate(()=>{state.settings.voicePack=false;});
  const r3=await p.evaluate(async w=>{window.__tts=[];await Sound.say("word:"+w,w,.82);return window.__tts;},word);
  ok(r3.length===1,"switch off -> device voice");
  await p.evaluate(()=>{state.settings.voicePack=true;openParent();document.querySelector('.tab[data-tab="set"]').click();});await p.waitForTimeout(300);
  await p.evaluate(()=>document.getElementById("optPack").scrollIntoView());await p.screenshot({path:"voice_row.png"});
  await p.evaluate(()=>{const n=document.querySelector("#soNo");if(n)n.click();document.getElementById("packDl").click();});await p.waitForTimeout(20000);
  const cached=await p.evaluate(async()=>{const c=await caches.open("wcv-voice-1");return (await c.keys()).length;});
  ok(cached>100,"voice clips cached for offline: "+cached);
  console.log("errors:",errs.length?errs:"none");await b.close();})();
