"use strict";window.WCV=window.WCV||{};
/* Wordcraft Valley: the one-minute reading check (Grown-up menu -> Progress -> One-minute reading check).
   NORMS     oral reading fluency, words correct per minute, from Hasbrouck & Tindal (2017), "An update to
             compiled ORF norms" (Technical Report 1702, Behavioral Research and Teaching, University of
             Oregon; ERIC ED594994). For each grade and season, the 10th, 25th, 50th, 75th and 90th
             percentiles. Grade 1 has no fall norm: most children cannot yet read connected text for a
             minute at the start of first grade. Kindergarten has none at all.
   PASSAGES  unpracticed grade-level stories, written for this check (they are not the passages the norms
             were built from, so a result is a guide, not a score). They are NOT decodable at a game level
             and are never shown in the game itself. Each check uses two, as the norms' authors advise
             (the average of two unpracticed readings), and the next check moves on to the next two.
   Plain ASCII only. */
WCV.fluency={
NORMS:{
  "1":{winter:[9,16,29,59,97],spring:[18,34,60,91,116]},
  "2":{fall:[23,36,50,84,111],winter:[35,59,84,109,131],spring:[43,72,100,124,148]}
},
PCT:[10,25,50,75,90],
PASSAGES:{
"1":[
{id:"g1hat",title:"The Lost Hat",text:"Sam had a red hat. He wore it every day. One windy morning, Sam went to the park with his dad. The wind was strong. It blew and blew. All at once, the wind took the hat right off his head! The hat flew over the grass. It landed by the pond. Sam ran after it, but the wind pushed it again. Now the hat was up in a tree. \"Dad, my hat is in the tree!\" Sam called. Dad came to look. The tree was too tall for him to reach. Then a big dog ran up to the tree. The dog barked and jumped. The branch shook, and the hat fell down. It landed right on the dog's head! Sam laughed and laughed. He gave the dog a pat and took back his hat. \"Thank you,\" he said. The dog wagged its tail and ran off to play."},
{id:"g1rain",title:"A Rainy Day",text:"It was raining when Mia woke up. She looked out the window. The sky was gray, and the street was wet. \"No park today,\" said Mom. Mia felt sad at first. Then she had an idea. She got a big box from the closet. She cut a door in one side. She cut two windows in the top. Mia painted the box blue and green. Now it was a little house. Her cat, Pip, walked in the door. He sat by a window and looked out. Mia got in too. It was a tight fit, but it was fun. They listened to the rain on the roof. Tap, tap, tap. Soon the rain stopped. The sun came out, and Mia saw a rainbow over the trees. \"Look, Pip!\" she said. \"Now we can go to the park after all.\""},
{id:"g1garden",title:"The Garden",text:"Ben and his grandma like to work in the garden. In the spring, they dig small holes in the dirt. Ben drops one seed in each hole. Grandma covers the seeds and pats the dirt down. Then Ben gets the watering can. He gives each seed a drink. Every day, Ben checks the garden. At first, he sees only dirt. After a week, he sees tiny green plants. \"They are growing!\" Ben shouts. The plants get bigger and bigger. Some grow long green beans. Some grow fat red tomatoes. One plant grows a pumpkin as big as a ball. In the fall, Ben and Grandma pick the food they grew. They make a pot of soup with the beans and tomatoes. Ben says it is the best soup he has ever had. Next spring, he wants to plant corn."},
{id:"g1bus",title:"The Bus Ride",text:"Every morning, Leo rides the bus to school. He waits at the corner with his friend Kim. The bus is big and yellow. When it stops, the door opens with a loud hiss. Leo and Kim climb up the steps. They say hello to the driver, Mr. Ray. Then they find a seat near the back. The bus makes a lot of stops. More and more kids get on. Some kids talk and laugh. Some kids read books. Leo likes to look out the window. He counts the red cars he can see. One day he counted twenty. The bus goes over a bridge and past a farm. Leo waves at the cows in the field. At last the bus stops in front of the school. Leo and Kim jump down the steps and run to their class."}
],
"2":[
{id:"g2fair",title:"The Science Fair",text:"Nora wanted to win a ribbon at the science fair. She thought about it for days. What could she study? One afternoon, she noticed that the ice in her lemonade melted faster in the sun than in the shade. That gave her an idea. Nora filled six cups with the same amount of ice. She put two cups in the sun, two in the shade, and two inside the freezer. Every ten minutes, she checked the cups and wrote down what she saw. The ice in the sun melted first. It turned to water in less than an hour. The ice in the shade took much longer. The ice in the freezer did not melt at all. Nora made a chart with bright colors to show her results. She practiced explaining her project to her brother. At the fair, a judge asked her why the sun made the ice melt faster. Nora explained that sunlight warms things up. The judge smiled and wrote something on her clipboard. At the end of the day, Nora got a blue ribbon. She could not stop grinning all the way home."},
{id:"g2puppy",title:"The New Puppy",text:"When the Garcia family brought home a new puppy, everyone was excited. The puppy was small and brown with one white ear. They named him Biscuit. On the first night, Biscuit cried in his bed in the kitchen. Marco, the oldest child, could not sleep. He crept downstairs and sat beside the little dog. He talked to Biscuit in a soft voice until the puppy closed his eyes. The next morning, Marco made a plan. He would help Biscuit feel safe in his new home. He put an old shirt in the puppy's bed so it would smell like the family. Each day after school, Marco taught Biscuit something new. First he learned to sit. Then he learned to come when he was called. Learning to stay was the hardest of all. Biscuit kept wiggling and jumping up. Marco was patient and gave him a treat whenever he did it right. By the end of the month, Biscuit could stay for a whole minute. The family was proud of them both, and Biscuit never cried at night again."},
{id:"g2light",title:"The Lighthouse",text:"Long ago, a tall lighthouse stood on a rocky island near the shore. A keeper named Ada lived there with her father. Each evening, before the sun went down, they climbed the winding stairs to the top. There were one hundred steps, and Ada counted every one. At the top, they cleaned the big glass lens until it sparkled. Then they lit the lamp. All night long, the light turned around and around. It warned the ships to stay away from the dangerous rocks. One stormy night, the wind howled and the waves crashed against the island. Ada's father was sick in bed with a fever. Ada knew the ships still needed the light. She took a lantern and climbed the stairs alone. Her legs were tired, but she did not stop. When she reached the top, she lit the lamp and watched it shine through the rain. Far out at sea, a fishing boat turned away from the rocks just in time. The next day, the fishermen came to thank Ada. They said she was the bravest keeper on the coast."},
{id:"g2museum",title:"A Trip to the Museum",text:"On Saturday, Jamal's class took a trip to the natural history museum. As soon as they walked through the doors, they saw a giant dinosaur skeleton. It was so tall that its head almost touched the ceiling. Their guide told them it was a plant eater that lived millions of years ago. Next, the class visited a room full of rocks and gems. Some of the rocks glowed under a special light. Jamal's favorite was a purple stone that sparkled like stars. After that, they walked through a hall with animals from around the world. There was a polar bear, a family of elephants, and a tiny hummingbird. The guide explained that each animal is suited to the place where it lives. The polar bear has thick fur to stay warm in the snow. At lunch, the students sat on the steps outside and talked about what they had seen. On the bus ride home, Jamal drew a picture of the dinosaur in his notebook. He decided that one day he wanted to dig for fossils himself."}
]
}
};
