/* Wordcraft Valley: the words.
   WORDS     every word: w the word, p its sound tiles, t its level (1-12); tricky:1 for a heart word (the kindergarten
             checklist is among them); the comments below say the rest. Custom words from the Grown-up menu are
             added at run time (allWords() in index.html).
   WORD_ART  the picture for a word, an ART id (drawWord in index.html draws it), finished by the Object.assign lines.
   Loaded before the game script (the <script src> tags in index.html), and in sw.js's SHELL list for offline play.
   Plain data only, and ASCII only: anything else is written as \uXXXX. tests/page.js inlines it for the jsdom suites. */
"use strict";window.WCV=window.WCV||{};
WCV.words={
WORDS:[
  {w:"cat",p:["c","a","t"],t:1},{w:"hat",p:["h","a","t"],t:1},{w:"bat",p:["b","a","t"],t:1},
  {w:"map",p:["m","a","p"],t:1},{w:"cap",p:["c","a","p"],t:1},{w:"pan",p:["p","a","n"],t:1},
  {w:"log",p:["l","o","g"],t:1},{w:"dog",p:["d","o","g"],t:1},{w:"pot",p:["p","o","t"],t:1},
  {w:"mop",p:["m","o","p"],t:1},{w:"rock",p:["r","o","ck"],t:1},{w:"box",p:["b","o","x"],t:1},
  {w:"fox",p:["f","o","x"],t:1},{w:"sock",p:["s","o","ck"],t:1},
  {w:"pig",p:["p","i","g"],t:2},{w:"bin",p:["b","i","n"],t:2},{w:"bed",p:["b","e","d"],t:2},
  {w:"hen",p:["h","e","n"],t:2},{w:"pen",p:["p","e","n"],t:2},{w:"net",p:["n","e","t"],t:2},
  {w:"web",p:["w","e","b"],t:2},{w:"egg",p:["e","gg"],t:2},{w:"sun",p:["s","u","n"],t:2},
  {w:"bug",p:["b","u","g"],t:2},{w:"cup",p:["c","u","p"],t:2},{w:"bus",p:["b","u","s"],t:2},
  {w:"jet",p:["j","e","t"],t:2},{w:"nut",p:["n","u","t"],t:2},
  {w:"ship",p:["sh","i","p"],t:3},{w:"shop",p:["sh","o","p"],t:3},{w:"fish",p:["f","i","sh"],t:3},
  {w:"dish",p:["d","i","sh"],t:3},{w:"chip",p:["ch","i","p"],t:3},{w:"chop",p:["ch","o","p"],t:3},
  {w:"bath",p:["b","a","th"],t:3},{w:"duck",p:["d","u","ck"],t:3},{w:"shell",p:["sh","e","ll"],t:3},
  {w:"chick",p:["ch","i","ck"],t:3},{w:"whale",p:["wh","a_e","l"],t:3},{w:"thumb",p:["th","u","mb"],t:3},
  // Tier 4 - consonant blends (two sounds side by side, both heard)
  {w:"frog",p:["f","r","o","g"],t:4},{w:"crab",p:["c","r","a","b"],t:4},{w:"drum",p:["d","r","u","m"],t:4},
  {w:"flag",p:["f","l","a","g"],t:4},{w:"nest",p:["n","e","s","t"],t:4},{w:"tent",p:["t","e","n","t"],t:4},
  {w:"plum",p:["p","l","u","m"],t:4},{w:"truck",p:["t","r","u","ck"],t:4},{w:"tree",p:["t","r","ee"],t:4},
  {w:"grass",p:["g","r","a","ss"],t:4},{w:"snow",p:["s","n","ow"],t:4},{w:"stone",p:["s","t","o_e","n"],t:4},
  // Tier 5 - magic e: the split digraph is one tile, said as the long vowel
  {w:"cake",p:["c","a_e","k"],t:5},{w:"bike",p:["b","i_e","k"],t:5},{w:"rope",p:["r","o_e","p"],t:5},
  {w:"kite",p:["k","i_e","t"],t:5},{w:"bone",p:["b","o_e","n"],t:5},{w:"gate",p:["g","a_e","t"],t:5},
  {w:"lake",p:["l","a_e","k"],t:5},{w:"well",p:["w","e","ll"],t:5},{w:"bell",p:["b","e","ll"],t:5},
  {w:"wolf",p:["w","o","l","f"],t:4},{w:"hawk",p:["h","aw","k"],t:5},{w:"claw",p:["c","l","aw"],t:5},
  {w:"croc",p:["c","r","o","c"],t:4},{w:"snail",p:["s","n","ai","l"],t:5},
  // vehicles - reading one of these unlocks that vehicle
  {w:"van",p:["v","a","n"],t:1},{w:"cab",p:["c","a","b"],t:1},
  {w:"sled",p:["s","l","e","d"],t:4},{w:"rocket",p:["r","o","ck","e","t"],t:4,syl:[3]},
  {w:"car",p:["c","ar"],t:5},{w:"jeep",p:["j","ee","p"],t:5},{w:"boat",p:["b","oa","t"],t:5},
  {w:"train",p:["t","r","ai","n"],t:5},{w:"plane",p:["p","l","a_e","n"],t:5},
  // Tricky words: the part in a heart can't be sounded out and is learned by heart.
  // A tile written "e:uh" shows "e" but says "uh"; "e:" is silent.
  {w:"the",p:["th:dh","e:uh"],t:1,tricky:1},{w:"a",p:["a:uh"],t:1,tricky:1},{w:"I",p:["I:eye"],t:1,tricky:1},
  {w:"is",p:["i","s:z"],t:1,tricky:1},{w:"to",p:["t","o:oo"],t:1,tricky:1},
  // Kindergarten tricky word checklist (from his class): all at the base level,
  // the part that doesn't sound out is a heart tile (learn it by heart)
  {w:"one",p:["o:wu","n","e:"],t:1,tricky:1},{w:"once",p:["o:wu","n","ce:s"],t:1,tricky:1},
  {w:"from",p:["f","r","o:u","m"],t:1,tricky:1},{w:"here",p:["h","e:ee","re:r"],t:1,tricky:1},
  {w:"three",p:["th","r","ee"],t:1,tricky:1},{w:"when",p:["wh","e","n"],t:1,tricky:1},
  {w:"word",p:["w","or:er","d"],t:1,tricky:1},{w:"blue",p:["b","l","ue:oo"],t:1,tricky:1},
  {w:"why",p:["wh","y:eye"],t:1,tricky:1},{w:"yellow",p:["y","e","ll","ow:oh"],t:1,tricky:1},
  {w:"be",p:["b","e:ee"],t:1,tricky:1},{w:"look",p:["l","oo","k"],t:1,tricky:1},
  {w:"their",p:["th:dh","ei:e","r"],t:1,tricky:1},{w:"little",p:["l","i","tt:t","le"],t:1,tricky:1},
  {w:"down",p:["d","ow:ou","n"],t:1,tricky:1},{w:"which",p:["wh","i","ch"],t:1,tricky:1},
  {w:"by",p:["b","y:eye"],t:1,tricky:1},{w:"out",p:["ou","t"],t:1,tricky:1},
  {w:"your",p:["y","our:or"],t:1,tricky:1},{w:"funny",p:["f","u","nn:n","y:ee"],t:1,tricky:1},
  {w:"says",p:["s","ay:e","s:z"],t:1,tricky:1},
  {w:"was",p:["w","a:o","s:z"],t:1,tricky:1},{w:"he",p:["h","e:ee"],t:1,tricky:1},{w:"she",p:["sh","e:ee"],t:1,tricky:1},
  {w:"we",p:["w","e:ee"],t:1,tricky:1},{w:"me",p:["m","e:ee"],t:1,tricky:1},{w:"my",p:["m","y:eye"],t:1,tricky:1},
  {w:"go",p:["g","o:oh"],t:2,tricky:1},{w:"no",p:["n","o:oh"],t:1,tricky:1},{w:"so",p:["s","o:oh"],t:1,tricky:1},
  {w:"his",p:["h","i","s:z"],t:2,tricky:1},
  {w:"said",p:["s","ai:e","d"],t:1,tricky:1},{w:"you",p:["y","ou:oo"],t:1,tricky:1},{w:"of",p:["o:u","f:v"],t:1,tricky:1},
  {w:"do",p:["d","o:oo"],t:3,tricky:1},{w:"are",p:["are:ar"],t:1,tricky:1},{w:"they",p:["th:dh","ey:ay"],t:1,tricky:1},
  {w:"have",p:["h","a","ve:v"],t:3,tricky:1},{w:"all",p:["a:aw","ll"],t:1,tricky:1},
  {w:"come",p:["c","o:u","m","e:"],t:4,tricky:1},{w:"some",p:["s","o:u","m","e:"],t:4,tricky:1},
  {w:"what",p:["wh","a:u","t"],t:1,tricky:1},{w:"put",p:["p","u:oo","t"],t:4,tricky:1},
  // Tier 6 - bossy r: ar, or, er / ir / ur
  {w:"star",p:["s","t","ar"],t:6},{w:"jar",p:["j","ar"],t:6},{w:"barn",p:["b","ar","n"],t:6},{w:"shark",p:["sh","ar","k"],t:6},
  {w:"fork",p:["f","or","k"],t:6},{w:"corn",p:["c","or","n"],t:6},{w:"horse",p:["h","or","s","e:"],t:6},{w:"shorts",p:["sh","or","t","s"],t:6},
  {w:"bird",p:["b","ir","d"],t:6},{w:"shirt",p:["sh","ir","t"],t:6},{w:"girl",p:["g","ir","l"],t:6},{w:"surf",p:["s","ur","f"],t:6},
  {w:"her",p:["h","er"],t:6},{w:"fur",p:["f","ur"],t:6},
  // Tier 7 - vowel teams: ai, ee, ea, oa, ow, oo, igh, ou / ow
  {w:"rain",p:["r","ai","n"],t:7},{w:"mail",p:["m","ai","l"],t:7},
  {w:"sheep",p:["sh","ee","p"],t:7},{w:"bee",p:["b","ee"],t:7},{w:"feet",p:["f","ee","t"],t:7},{w:"seed",p:["s","ee","d"],t:7},
  {w:"leaf",p:["l","ea","f"],t:7},{w:"peach",p:["p","ea","ch"],t:7},{w:"sea",p:["s","ea"],t:7},
  {w:"goat",p:["g","oa","t"],t:7},{w:"coat",p:["c","oa","t"],t:7},{w:"road",p:["r","oa","d"],t:7},{w:"soap",p:["s","oa","p"],t:7},
  {w:"bow",p:["b","ow"],t:7},{w:"moon",p:["m","oo","n"],t:7},{w:"boot",p:["b","oo","t"],t:7},{w:"spoon",p:["s","p","oo","n"],t:7},
  {w:"night",p:["n","igh","t"],t:7},{w:"light",p:["l","igh","t"],t:7},
  {w:"cow",p:["c","ow:ou"],t:7},{w:"house",p:["h","ou","s","e:"],t:7},{w:"mouse",p:["m","ou","s","e:"],t:7},{w:"cloud",p:["c","l","ou","d"],t:7},
  // Tier 8 - two-part words, read one part at a time (syl = where the break falls)
  {w:"sunset",p:["s","u","n","s","e","t"],t:8,syl:[3]},{w:"picnic",p:["p","i","c","n","i","c"],t:8,syl:[3]},
  {w:"rabbit",p:["r","a","b","b","i","t"],t:8,syl:[3]},{w:"robot",p:["r","o:oh","b","o","t"],t:8,syl:[2]},
  {w:"pumpkin",p:["p","u","m","p","k","i","n"],t:8,syl:[4]},{w:"hotdog",p:["h","o","t","d","o","g"],t:8,syl:[3]},
  {w:"cupcake",p:["c","u","p","c","a_e","k"],t:8,syl:[3]},{w:"lemon",p:["l","e","m","o:u","n"],t:8,syl:[3]},
  {w:"magnet",p:["m","a","g","n","e","t"],t:8,syl:[3]},{w:"sandwich",p:["s","a","n","d","w","i","ch"],t:8,syl:[4]},
  {w:"backpack",p:["b","a","ck","p","a","ck"],t:8,syl:[3]},{w:"turtle",p:["t","ur","t","le"],t:8,syl:[2]},
  {w:"burger",p:["b","ur","g","er"],t:8,syl:[2]},{w:"tennis",p:["t","e","n","n","i","s"],t:8,syl:[3]},
  {w:"dragon",p:["d","r","a","g","o:u","n"],t:8,syl:[3]},
  {w:"sub",p:["s","u","b"],t:2},{w:"tram",p:["t","r","a","m"],t:4},{w:"dump",p:["d","u","m","p"],t:4},
  {w:"crane",p:["c","r","a_e","n"],t:5},
  // Tier 9 - endings; 10 - soft c/g and y; 11 - compound words; 12 - silent letters and contractions
  {w:"fishing",p:["f", "i", "sh", "i", "ng"],t:9,syl:[3]},
  {w:"running",p:["r", "u", "nn", "i", "ng"],t:9,syl:[3]},
  {w:"swimming",p:["s", "w", "i", "mm", "i", "ng"],t:9,syl:[4]},
  {w:"sleeping",p:["s", "l", "ee", "p", "i", "ng"],t:9,syl:[4]},
  {w:"camping",p:["c", "a", "m", "p", "i", "ng"],t:9,syl:[4]},
  {w:"surfing",p:["s", "ur", "f", "i", "ng"],t:9,syl:[3]},
  {w:"singing",p:["s", "i", "ng", "i", "ng"],t:9,syl:[3]},
  {w:"painting",p:["p", "ai", "n", "t", "i", "ng"],t:9,syl:[4]},
  {w:"jumped",p:["j", "u", "m", "p", "ed:t"],t:9,syl:[4]},
  {w:"landed",p:["l", "a", "n", "d", "e:i", "d"],t:9,syl:[4]},
  {w:"rested",p:["r", "e", "s", "t", "e:i", "d"],t:9,syl:[4]},
  {w:"wished",p:["w", "i", "sh", "ed:t"],t:9,syl:[3]},
  {w:"yelled",p:["y", "e", "ll", "ed:d"],t:9,syl:[3]},
  {w:"there",p:["th:dh", "e", "re:r"],t:1,tricky:1},
  {w:"where",p:["wh", "e", "re:r"],t:1,tricky:1},
  {w:"were",p:["w", "ere:er"],t:1,tricky:1},
  {w:"city",p:["c:s", "i", "t", "y:ee"],t:10,syl:[2]},
  {w:"mice",p:["m", "i_e", "c:s"],t:10},
  {w:"ice",p:["i_e", "c:s"],t:10},
  {w:"face",p:["f", "a_e", "c:s"],t:10},
  {w:"rice",p:["r", "i_e", "c:s"],t:10},
  {w:"gem",p:["g:j", "e", "m"],t:10},
  {w:"page",p:["p", "a_e", "g:j"],t:10},
  {w:"happy",p:["h", "a", "pp", "y:ee"],t:10,syl:[2]},
  {w:"puppy",p:["p", "u", "pp", "y:ee"],t:10,syl:[2]},
  {w:"bunny",p:["b", "u", "nn", "y:ee"],t:10,syl:[2]},
  {w:"candy",p:["c", "a", "n", "d", "y:ee"],t:10,syl:[3]},
  {w:"baby",p:["b", "a:ay", "b", "y:ee"],t:10,syl:[2]},
  {w:"fly",p:["f", "l", "y:eye"],t:10},
  {w:"sky",p:["s", "k", "y:eye"],t:10},
  {w:"cry",p:["c", "r", "y:eye"],t:10},
  {w:"two",p:["t", "wo:oo"],t:1,tricky:1},
  {w:"want",p:["w", "a:o", "n", "t"],t:10,tricky:1},
  {w:"rainbow",p:["r", "ai", "n", "b", "ow"],t:11,syl:[3],comp:1},
  {w:"popcorn",p:["p", "o", "p", "c", "or", "n"],t:11,syl:[3],comp:1},
  {w:"snowman",p:["s", "n", "ow", "m", "a", "n"],t:11,syl:[3],comp:1},
  {w:"bathtub",p:["b", "a", "th", "t", "u", "b"],t:11,syl:[3],comp:1},
  {w:"mailbox",p:["m", "ai", "l", "b", "o", "x"],t:11,syl:[3],comp:1},
  {w:"teapot",p:["t", "ea", "p", "o", "t"],t:11,syl:[2],comp:1},
  {w:"pancake",p:["p", "a", "n", "c", "a_e", "k"],t:11,syl:[3],comp:1},
  {w:"sailboat",p:["s", "ai", "l", "b", "oa", "t"],t:11,syl:[3],comp:1},
  {w:"seashell",p:["s", "ea", "sh", "e", "ll"],t:11,syl:[2],comp:1},
  {w:"sunfish",p:["s", "u", "n", "f", "i", "sh"],t:11,syl:[3],comp:1},
  {w:"could",p:["c", "ou:oo", "l:", "d"],t:11,tricky:1},
  {w:"would",p:["w", "ou:oo", "l:", "d"],t:11,tricky:1},
  {w:"knot",p:["kn:n", "o", "t"],t:12},
  {w:"knee",p:["kn:n", "ee"],t:12},
  {w:"knife",p:["kn:n", "i_e", "f"],t:12},
  {w:"write",p:["wr:r", "i_e", "t"],t:12},
  {w:"wrench",p:["wr:r", "e", "n", "ch"],t:12},
  {w:"phone",p:["ph:f", "o_e", "n"],t:12},
  {w:"lamb",p:["l", "a", "mb"],t:12},
  {w:"can't",p:["c", "a", "n", "'t:t"],t:12,tricky:1,contr:1},
  {w:"don't",p:["d", "o:oh", "n", "'t:t"],t:12,tricky:1,contr:1},
  {w:"it's",p:["i", "t", "'s:s"],t:12,tricky:1,contr:1},
  {w:"I'm",p:["I:eye", "'m:m"],t:12,tricky:1,contr:1}
],
WORD_ART:{cat:"cat",hat:"hat",bat:"bat",map:"map",cap:"cap",pan:"pan",log:"wood",dog:"dog",
  pot:"pot",mop:"mop",rock:"stone",box:"box",fox:"fox",sock:"sock",pig:"pig",bin:"bin",bed:"bed",
  hen:"hen",pen:"pen",net:"net",web:"web",egg:"egg",sun:"sun",bug:"bug",cup:"cup",bus:"bus",
  jet:"jet",nut:"nut",ship:"ship",shop:"shop",fish:"fish",dish:"dish",chip:"chip",chop:"chop",
  bath:"bath",duck:"duck",shell:"shell",chick:"chick",whale:"whale",thumb:"thumb",
  tree:"tree",frog:"frog",rain:"water",moon:"crystal",pine:"pine",sand:"sand",
  crab:"crab",drum:"drum",flag:"flag",nest:"nest",tent:"tent",plum:"plum",truck:"truck",grass:"grass",
  cake:"cake",bike:"bike",rope:"rope",kite:"kite",bone:"bone",gate:"gate",lake:"lake",stone:"stone",
  snow:"snow",fence:"fence",door:"door",well:"well",bell:"bell",barn:"barn",boat:"ship",owl:"owl",
  wolf:"wolf",hawk:"hawk",bear:"bear",claw:"crab",dragon:"dragon",croc:"croc",shark:"shark",
  lion:"lion",tiger:"tiger",boar:"boar",crab:"crab",snail:"snail",owl:"owl"}
};
Object.assign(WCV.words.WORD_ART,{"fishing": "x_fishing", "running": "x_running", "swimming": "x_swimming", "sleeping": "x_sleeping", "camping": "x_camping", "surfing": "x_surfing", "singing": "x_singing", "painting": "x_painting", "city": "x_city", "mice": "x_mice", "ice": "x_ice", "rice": "x_rice", "gem": "x_gem", "page": "x_page", "happy": "x_happy", "puppy": "x_puppy", "bunny": "x_bunny", "candy": "x_candy", "baby": "x_baby", "fly": "x_fly", "cry": "x_cry", "rainbow": "x_rainbow", "popcorn": "x_popcorn", "snowman": "x_snowman", "bathtub": "x_bathtub", "mailbox": "x_mailbox", "teapot": "x_teapot", "pancake": "x_pancake", "seashell": "x_seashell", "sunfish": "x_sunfish", "knot": "x_knot", "knee": "x_knee", "knife": "x_knife", "write": "x_write", "wrench": "x_wrench", "phone": "x_phone", "lamb": "x_lamb", "sailboat": "v_sailboat"});
// vehicle words use the vehicle artwork, so the picture matches the toy he unlocks
Object.assign(WCV.words.WORD_ART,{bus:"v_bus",jet:"v_plane",ship:"v_ship",truck:"v_truck",bike:"v_bike",
  boat:"v_sailboat",van:"v_van",cab:"v_taxi",car:"v_car",jeep:"v_suv",sled:"v_sled",
  train:"v_train",rocket:"v_rocket",plane:"v_plane",sub:"v_submarine",tram:"v_tram",dump:"v_dumptruck",crane:"v_crane"});
// later levels
Object.assign(WCV.words.WORD_ART,{backpack:"w_backpack",bee:"w_bee",bird:"w_bird",boot:"w_boot",bow:"w_bow",burger:"w_burger",cloud:"w_cloud",coat:"w_coat",corn:"w_corn",cow:"w_cow",cupcake:"w_cupcake",feet:"w_feet",fork:"w_fork",girl:"w_girl",goat:"w_goat",horse:"w_horse",hotdog:"w_hotdog",house:"w_house",jar:"w_jar",leaf:"w_leaf",lemon:"w_lemon",light:"w_light",magnet:"w_magnet",mail:"w_mail",moon:"w_moon",mouse:"w_mouse",night:"w_night",peach:"w_peach",picnic:"w_picnic",pumpkin:"w_pumpkin",rabbit:"w_rabbit",rain:"w_rain",road:"w_road",robot:"w_robot",sandwich:"w_sandwich",sea:"w_sea",seed:"w_seed",sheep:"w_sheep",shirt:"w_shirt",shorts:"w_shorts",soap:"w_soap",spoon:"w_spoon",star:"w_star",sunset:"w_sunset",surf:"w_surf",tennis:"w_tennis",turtle:"w_turtle"});
